name: imgpipe
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=3
  - eeglabio=0.0.2.post4
  - glib=2.78.4
  - glib-tools=2.78.4
  - mayavi=4.8.1
  - mne-base=1.6
  - mne-qt-browser=0.6
  - pip=24.0
  - pyface=8
  - pymatreader
  - pyopengl=3.1.6
  - pyqt=5.15
  - pyqt5-sip=12.12
  - pyqtgraph=0.13
  - python=3.12
  - pyvista=0.43
  - pyvistaqt=0.11
  - qt=5.15.8
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - scikit-image=0.22.0
  - scikit-learn=1.4
  - scipy=1.12.0
  - tk=8.6.13
  - vtk=9.2.6
  - vtk-base=9.2.6
  - vtk-io-ffmpeg=9.2.6
  - pip:
      - ipyevents==2.0.2
      - mpmath==1.3.0
      - nipy==0.6.0
      - sympy==1.12
      - transforms3d==0.4.1
